apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
data:
  init.sql: |
    CREATE TABLE todo_list (
        id UUID PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        description TEXT
    );
